
package my_code;

import java.awt.Component;
import java.awt.Image;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import my_code.cars;
import vmm.Dbloader;

/**
 *
 * @author verma
 */
public class AdminManageCars extends javax.swing.JFrame {

    ArrayList<cars> al;
    mytablemodel tm;

    public AdminManageCars() {
        initComponents();
        tm = new mytablemodel();
        al = new ArrayList<>();
        table.setModel(tm);
        call();
        table.setRowHeight(100);
        table.getColumnModel().getColumn(8).setCellRenderer(new ImageRenderer());
    }

    void call() {
        try {

            ResultSet rs = Dbloader.executeSql("Select * from admin_car");
            
            while(rs.next())
            {
              String name = rs.getString("car_name");
              String brand=rs.getString("car_company");
              String body=rs.getString("body_type");
               
              String fuel=rs.getString("fuel_type");
              Integer security=rs.getInt("security");
              Integer rentwithdriver=rs.getInt("rent_with_driver");
              Integer rentwithoutdriver=rs.getInt("rent_without_driver");
              String description=rs.getString("description");
              String photo=rs.getString("photo");
              al.add(new cars( name,  brand,  fuel,  body, security,  rentwithdriver,  rentwithoutdriver,  description,  photo));
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
        class ImageRenderer extends DefaultTableCellRenderer {

            JLabel lbl = new JLabel();
            ImageIcon icon = new ImageIcon();

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                if (value instanceof String) {
                    String photoPath = (String) value;
                    System.out.println("Photo Path " + photoPath);
                    icon = new ImageIcon(photoPath);
                    Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                    lbl.setIcon(new ImageIcon(img));
                } else {
                    lbl.setIcon(null);
                }
                return lbl;
            }
        }
        class mytablemodel extends AbstractTableModel {

            @Override
            public int getRowCount() {
                return al.size();
            }

            @Override
            public int getColumnCount() {
                return 9;
            }

            @Override
            public Object getValueAt(int i, int j) {
                cars c = al.get(i);
                if (j == 0) {
                    return c.name;
                } else if (j == 1) {
                    return c.body;
                } else if (j == 2) {
                    return c.fuel;
                } else if (j == 3) {
                    return c.brand;
                } else if (j == 4) {
                    return c.description;
                } else if (j == 5) {
                    return c.rentwithdriver;
                } else if (j == 6) {
                    return c.rentwithoutdriver;
                } else if (j == 7) {
                    return c.security;
                } else {
                    return c.photo;
                }

            }

            public String getColumnName(int j) {
                String col[] = {"Name", "Type", "Fuel", "Brand", "Desc", "Rent", "Driver Rent", "Security", "Photo"};
                return col[j];
            }

        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bt1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bt2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lb1.setText("YOUR_ALL_CARS");
        getContentPane().add(lb1);
        lb1.setBounds(230, 20, 200, 16);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 60, 610, 280);

        bt1.setText("Add cars");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(140, 370, 110, 40);
        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(72, 60, 480, 250);

        bt2.setText("remove car");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(445, 363, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        Admin_AddCar obj = new Admin_AddCar();
        obj.setVisible(true);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        int row=table.getSelectedRow();
        int val=(int) table.getValueAt(row, 9);
        try {
            ResultSet rs=Dbloader.executeSql("select * from admin_cars where car_id="+val+"");
            if(rs.next())
            {
                rs.deleteRow();
                tm.fireTableDataChanged();
            }
        } catch (Exception ex) {
            //Logger.getLogger(AdminManageCars.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    
        
    }//GEN-LAST:event_bt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminManageCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
