/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_code;
import java.awt.Image;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import java.sql.*;
import vmm.Dbloader;
/**
 *
 * @author verma
 */
public class Admin_AddCar extends javax.swing.JFrame {
    
   

    File ph;
     String description;
    /**
     * Creates new form Admin_AddCar
     */
    public Admin_AddCar() {
        initComponents();
        setSize(600,400);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        lb9 = new javax.swing.JLabel();
        jb10 = new javax.swing.JLabel();
        bt2 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        photo = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lb1.setText("Add_NewCar");
        getContentPane().add(lb1);
        lb1.setBounds(260, 0, 230, 50);

        lb2.setText("Car Name");
        getContentPane().add(lb2);
        lb2.setBounds(80, 80, 70, 16);

        lb3.setText("Car Company");
        getContentPane().add(lb3);
        lb3.setBounds(80, 120, 80, 16);

        lb4.setText("Body Type");
        getContentPane().add(lb4);
        lb4.setBounds(80, 160, 70, 16);

        lb5.setText("Fuel Type");
        getContentPane().add(lb5);
        lb5.setBounds(80, 200, 60, 16);

        lb6.setText("Security");
        getContentPane().add(lb6);
        lb6.setBounds(80, 240, 60, 16);

        lb7.setText("Rent With Driver");
        getContentPane().add(lb7);
        lb7.setBounds(80, 280, 90, 16);

        lb8.setText("Rent Without Driver");
        getContentPane().add(lb8);
        lb8.setBounds(80, 320, 110, 16);

        lb9.setText("Description");
        getContentPane().add(lb9);
        lb9.setBounds(80, 360, 90, 16);

        jb10.setText("Photo");
        getContentPane().add(jb10);
        jb10.setBounds(90, 480, 50, 16);

        bt2.setText("Add");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(280, 580, 72, 23);

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(290, 80, 170, 22);
        getContentPane().add(tf2);
        tf2.setBounds(290, 120, 170, 22);

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sedan", "suv", "jeep", "sports" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(290, 160, 170, 22);

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "petrol", "disel", "ev", " " }));
        getContentPane().add(cb2);
        cb2.setBounds(290, 200, 170, 22);
        getContentPane().add(tf3);
        tf3.setBounds(290, 240, 170, 22);
        getContentPane().add(tf4);
        tf4.setBounds(290, 270, 170, 22);
        getContentPane().add(tf5);
        tf5.setBounds(290, 310, 170, 22);

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 350, 140, 90);
        getContentPane().add(photo);
        photo.setBounds(230, 450, 100, 90);

        bt1.setText("Choose Photo");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(460, 470, 140, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
       JFileChooser jfc=new JFileChooser();
        int ans=jfc.showOpenDialog(this);
        if(ans==JFileChooser.APPROVE_OPTION)
        {
           ph=jfc.getSelectedFile();
            ImageIcon ic=new ImageIcon(ph.getPath());
            Image ic1=ic.getImage().getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ic2=new ImageIcon(ic1);
            photo.setIcon(ic2);
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tf1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        String name=tf1.getText().trim();
        String path=SaveFile.saveFile(ph);
        String  company=tf2.getText().trim();
        int security=Integer.parseInt(tf3.getText().trim());
        int rentwithdriver=Integer.parseInt(tf4.getText().trim());
        
        int rentwithoutdriver=Integer.parseInt(tf4.getText().trim());
        String bodytype=(String) cb1.getSelectedItem();
        String fueltype=(String) cb2.getSelectedItem();
        String description=ta1.getText();
        
        try {
            
            
            // TODO add your handling code here:
            ResultSet rs=(ResultSet)Dbloader.executeSql("");
            rs.moveToInsertRow();
            rs.updateString("car_name", name);
            rs.updateString("car_company", company);
            rs.updateInt("security", security);
            rs.updateString("photo", path);
            rs.updateString("body_type",bodytype);
            rs.updateString("fuel_type", fueltype);
            rs.updateString("description",description);
           // int rentwithdriver = 0;
           
            rs.updateInt("rent_with_driver",rentwithdriver);
            rs.updateInt("rent_without_driver",rentwithoutdriver);
           
            rs.insertRow();
        } catch (Exception ex) {
ex.printStackTrace();
        }
    }//GEN-LAST:event_bt2ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_AddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_AddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_AddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_AddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_AddCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jb10;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JLabel photo;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    // End of variables declaration//GEN-END:variables
}
