/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package my_code;

/**
 *
 * @author verma
 */
public class design_1 extends javax.swing.JPanel {

    /**
     * Creates new form design_1
     */
    public design_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        rent = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setLayout(null);

        name.setText("jLabel1");
        add(name);
        name.setBounds(30, 20, 100, 20);

        photo.setText("jLabel2");
        add(photo);
        photo.setBounds(60, 90, 150, 150);

        lb3.setText("rent");
        add(lb3);
        lb3.setBounds(10, 320, 70, 30);

        rent.setText("jLabel4");
        add(rent);
        rent.setBounds(120, 320, 110, 30);

        jPanel1.setLayout(null);
        add(jPanel1);
        jPanel1.setBounds(0, 0, 310, 400);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lb3;
    public javax.swing.JLabel name;
    public javax.swing.JLabel photo;
    public javax.swing.JLabel rent;
    // End of variables declaration//GEN-END:variables
}
