/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_code;

import java.awt.Image;
import java.io.File;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import my_code.SaveFile;
import vmm.Dbloader;

/**
 *
 * @author verma
 */
public class new_user extends javax.swing.JFrame {

    /**
     * Creates new form new_user
     */
File ph;
JFileChooser jfc=new JFileChooser();
    public new_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        cb1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("new_user");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 30, 130, 32);

        lb2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb2.setText("name");
        getContentPane().add(lb2);
        lb2.setBounds(130, 100, 40, 20);

        lb3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb3.setText("e_mail");
        getContentPane().add(lb3);
        lb3.setBounds(130, 140, 50, 20);

        lb4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb4.setText("password");
        getContentPane().add(lb4);
        lb4.setBounds(130, 180, 70, 20);

        lb5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb5.setText("mobile");
        getContentPane().add(lb5);
        lb5.setBounds(130, 230, 50, 20);

        lb6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb6.setText("gender");
        getContentPane().add(lb6);
        lb6.setBounds(130, 280, 50, 20);

        lb7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb7.setText("photo");
        getContentPane().add(lb7);
        lb7.setBounds(130, 330, 50, 20);
        getContentPane().add(photo);
        photo.setBounds(227, 320, 110, 80);

        bt1.setText("choose");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(450, 340, 90, 23);

        bt2.setText("add");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(320, 430, 72, 23);
        getContentPane().add(tf1);
        tf1.setBounds(280, 100, 180, 22);
        getContentPane().add(tf2);
        tf2.setBounds(280, 140, 180, 22);
        getContentPane().add(tf3);
        tf3.setBounds(280, 180, 180, 22);
        getContentPane().add(tf4);
        tf4.setBounds(280, 230, 180, 22);

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cb1);
        cb1.setBounds(280, 270, 180, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:JFileChooser jfc=new JFileChooser();
        int ans=jfc.showOpenDialog(this);
        if(ans==JFileChooser.APPROVE_OPTION)
        {
            ph=jfc.getSelectedFile();
            ImageIcon ic=new ImageIcon(ph.getPath());
            Image ic1=ic.getImage().getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ic2=new ImageIcon(ic1);
            photo.setIcon(ic2);
        }
                         
    
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
String name=tf1.getText().trim();
        String email=tf2.getText().trim();
        String password=tf3.getText().trim();
        String mobile=tf4.getText().trim();
        String gender=(String) cb1.getSelectedItem();
        String path=SaveFile.saveFile(ph);
  
  try {
            // TODO add your handling code here:
            ResultSet rs=(ResultSet) Dbloader.executeSql("Select * from user_home");
            rs.moveToInsertRow();
            rs.updateString("name", name);
            rs.updateString("photo", path);
            rs.updateString("email", email);
            rs.updateString("password", password);
            rs.updateString("mobile", mobile);
            rs.updateString("gender",gender);
            rs.updateString("photo", path);
      
            
            
            rs.insertRow();
            JOptionPane.showMessageDialog(null,"Success");
        } catch (Exception ex) {
            //Logger.getLogger(user_login.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
     
                                       

                                    

    
    }//GEN-LAST:event_bt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
}
