package my_code;
import java.awt.Dimension;
import java.awt.Image;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.ImageIcon;
import vmm.Dbloader;

/**
 *
 * @author verma
 */
public class user_home extends javax.swing.JFrame {

    /**
     * Creates new form user_home
     */
    public user_home() {
        initComponents();setSize(1800,2200);
        setVisible(true);
        call();
    }
void call()
{
    int x=10;
    int y=10;
    try
    {
     ResultSet rs = (ResultSet) Dbloader.executeSql("select * from admin_car");
     while(rs.next())
     {
     String name=rs.getString("car_name");
                System.out.println(name);
                String Photo=rs.getString("photo");
                System.out.println(Photo);
                int rent=rs.getInt("rent_with_driver");
                design_1 obj=new design_1();
                obj.name.setText(name);
                ImageIcon ic=new ImageIcon(Photo);
                Image ic1=ic.getImage().getScaledInstance(obj.photo.getWidth(), obj.photo.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon ic2=new ImageIcon(ic1);
                obj.photo.setIcon(ic2);
                obj.rent.setText(rent+"");
                obj.setBounds(x, y, 300, 380);
                x+=320;
                jp.add(obj);
                obj.repaint();
                jp.repaint();
        
    }
     jp.setPreferredSize(new Dimension(3900,400));
    }
    catch(Exception ex){
      // Logger.getLogger(user_home.class.getName()).log(Level.SEVERE, null, ex);
      ex.printStackTrace();
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jp = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("user_home");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 20, 130, 16);

        jp.setLayout(null);
        jScrollPane1.setViewportView(jp);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 80, 520, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp;
    // End of variables declaration//GEN-END:variables
}
